# date details cleaning

**Step 2:**<br>
Extract the orders data using the read_rds_table method you create earlier returning a pandas DataFrame.


**Step 3:**<br>
Create a method in DataCleaning called clean_orders_data which will clean the orders table data.

You should remove the columns, first_name, last_name and 1 to have the table in the correct form before uploading to the database.

You will see that the orders data contains column headers which are the same in other tables.

This table will act as the source of truth for your sales data and will be at the center of your star based database schema.

In [1]:
# need to mount Google Drive to be able to load data from it
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# import pandas and the RDS table that needs cleaning
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/001. Data Science/005. Ai Core/014. Multinational Data Centralization Project/date_details.json")

In [5]:
df.columns

Index(['Unnamed: 0', 'product_name', 'product_price', 'weight', 'category',
       'EAN', 'date_added', 'uuid', 'removed', 'product_code'],
      dtype='object')

In [6]:
df.head()

,Unnamed: 0,product_name,product_price,weight,category,EAN,date_added,uuid,removed,product_code
0,0,FurReal Dazzlin' Dimples My Playful Dolphin,£39.99,1.6kg,toys-and-games,7425710935115,2005-12-02,83dc0a69-f96f-4c34-bcb7-928acae19a94,Still_avaliable,R7-3126933h
1,1,Tiffany's World Day Out At The Park,£12.99,0.48kg,toys-and-games,487128731892,2006-01-09,712254d7-aea7-4310-aff8-8bcdd0aec7ff,Still_avaliable,C2-7287916l
2,2,Tiffany's World Pups Picnic Playset,£7.00,590g,toys-and-games,1945816904649,1997-03-29,b089ef6f-b628-4e37-811d-fffe0102ba64,Still_avaliable,S7-1175877v
3,3,Tiffany's World Wildlife Park Adventures,£12.99,540g,toys-and-games,1569790890899,2013-03-20,d55de422-8b98-47d6-9991-e4bc4c5c0cb0,Removed,D8-8421505n
4,4,Cosatto Cosy Dolls Pram,£30.00,1.91kg,toys-and-games,7142740213920,2007-12-23,7945b657-cb02-4cc5-96cf-f65ed0a8f235,Still_avaliable,B6-2596063a

In [ ]:
# at first, let's remove the columns are required by the excercise
df.drop(['first_name', 'last_name', '1'], axis = 1, inplace = True)

In [ ]:
df.head()

,Unnamed: 0,level_0,index,date_uuid,user_uuid,card_number,store_code,product_code,product_quantity
0,0,0,0,9476f17e-5d6a-4117-874d-9cdb38ca1fa6,93caf182-e4e9-4c6e-bebb-60a1a9dcf9b8,30060773296197,BL-8387506C,R7-3126933h,3
1,1,1,1,0423a395-a04d-4e4a-bd0f-d237cbd5a295,8fe96c3a-d62d-4eb5-b313-cf12d9126a49,349624180933183,WEB-1388012W,C2-7287916l,2
2,2,2,2,65187294-bb16-4519-adc0-787bbe423970,fc461df4-b919-48b2-909e-55c95a03fe6b,3529023891650490,CH-01D85C8D,S7-1175877v,2
3,3,3,3,579e21f7-13cb-436b-83ad-33687a4eb337,6104719f-ef14-4b09-bf04-fb0c4620acb0,213142929492281,CL-C183BE4B,D8-8421505n,2
4,4,4,4,00ab86c3-2039-4674-b9c1-adbcbbf525bd,9523a6d3-b2dd-4670-a51a-36aebc89f579,502067329974,SO-B5B9CB3B,B6-2596063a,2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120123 entries, 0 to 120122
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        120123 non-null  int64
 1   level_0           120123 non-null  int64
 2   index             120123 non-null  int64
 3   date_uuid         120123 non-null  object
 4   user_uuid         120123 non-null  object
 5   card_number       120123 non-null  int64
 6   store_code        120123 non-null  object
 7   product_code      120123 non-null  object
 8   product_quantity  120123 non-null  int64
dtypes: int64(5), object(4)
memory usage: 8.2+ MB

In [ ]:
df.duplicated().sum()

0

In [ ]:
df.isna().sum()

Unnamed: 0          0
level_0             0
index               0
date_uuid           0
user_uuid           0
card_number         0
store_code          0
product_code        0
product_quantity    0
dtype: int64

In [ ]:
#df[df['xxx'].isnull()]
#df = df[df['xxx'].notnull()]

In [ ]:
df['card_number'].astype(int)
# there shouldn't be anything strange with this column

0           30060773296197
1          349624180933183
2         3529023891650490
3          213142929492281
4             502067329974
                ...
120118        575421945446
120119    4971858637664481
120120    4971858637664481
120121    4971858637664481
120122    4971858637664481
Name: card_number, Length: 120123, dtype: int64

In [ ]:
df['store_code'].value_counts()

WEB-1388012W    26957
BE-09F94471       265
OB-FDC2CF69       261
CL-0FB1065C       255
CH-A44B48E6       251
                ...
LO-D54E72B5       181
BL-04FD6EF3       178
HI-BAD4DD1C       176
PO-47A01287       176
SU-B415327A       174
Name: store_code, Length: 441, dtype: int64

# Need doing
1. ...
2. ...
3. ...

# clean_orders_data Class

In [ ]:
df.drop(['first_name', 'last_name', '1'], axis = 1, inplace = True)